### ISSUE TITLE
Please help, probably a simple fix 

### ISSUE THREAD

**Issue by anna-trojanowska** [anna-trojanowska/exercise-2-scss#1]
Why why why can't I centre my buttons on the page?! I'm using inline-block, vertical-align, I tried to centre the text... it worked so easily last time without scss, I feel like I'm going crazy. 

Please take a look if you have a min! @ccmadrid @charlie-quinn
<img width="1186" alt="screen shot 2016-01-30 at 6 27 26 pm" src="https://cloud.githubusercontent.com/assets/6340298/12699147/2f14ee54-c77f-11e5-8922-ea2b8d4417dc.png">

**Comment by charlie-quinn** [comment]
closes #1

**Comment by charlie-quinn** [comment]
@anna-trojanowska close this issue! 😛
